In [1]:
import numpy as np

In [5]:
ndim = 4
dt = 1.

In [7]:
motion_mat = np.eye(2 * ndim, 2*ndim)
motion_mat

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

In [9]:
for i in range(ndim):
    motion_mat[i, ndim+i] = dt
    print(motion_mat)
print(f"Final motion matrix:\n{motion_mat}")

[[1. 0. 0. 0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]]
[[1. 0. 0. 0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]]
[[1. 0. 0. 0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]]
[[1. 0. 0. 0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]]
Final motion matrix:
[[1. 0. 0. 0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0. 0. 1.]
 [0

In [13]:
# update matrix or observation matrix
update_matrix = np.eye(ndim, 2*ndim)
print(f"The update matrix:\n {update_matrix}")

The update matrix:
 [[1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]]


In [33]:
# a sample detected object with [x,y, a, h]
# where (x,y) is current position and a,h are aspect ratio and height
measurement = np.array([53, 311, 83, 156])
mean_pos = [53, 311, 83, 156]
mean_vel = np.zeros_like(mean_pos)
mean = np.r_[mean_pos, mean_vel]
print(f"Value of mean\n: {mean}")

Value of mean
: [ 53 311  83 156   0   0   0   0]


In [25]:
measurement[3]

156

In [27]:
std_weight_position = 1. / 20
std_weight_velocity = 1. / 160
print(f"standard deviation weight postion: {std_weight_position}")
print(f"standard deviation weight velocity: {std_weight_velocity}")

standard deviation weight postion: 0.05
standard deviation weight velocity: 0.00625


In [31]:
std = [
            2 * std_weight_position * measurement[3],
            2 * std_weight_position * measurement[3],
            1e-2,
            2 * std_weight_position * measurement[3],
            10 * std_weight_velocity * measurement[3],
            10 * std_weight_velocity * measurement[3],
            1e-5,
            10 * std_weight_velocity * measurement[3]]
covariance = np.diag(np.square(std))

print(f"Shape of the covarience matrix: {covariance.shape}")
print(f"Covarience matrix:\n {covariance}")

Shape of the covarience matrix: (8, 8)
Covarience matrix:
 [[2.43360e+02 0.00000e+00 0.00000e+00 0.00000e+00 0.00000e+00 0.00000e+00
  0.00000e+00 0.00000e+00]
 [0.00000e+00 2.43360e+02 0.00000e+00 0.00000e+00 0.00000e+00 0.00000e+00
  0.00000e+00 0.00000e+00]
 [0.00000e+00 0.00000e+00 1.00000e-04 0.00000e+00 0.00000e+00 0.00000e+00
  0.00000e+00 0.00000e+00]
 [0.00000e+00 0.00000e+00 0.00000e+00 2.43360e+02 0.00000e+00 0.00000e+00
  0.00000e+00 0.00000e+00]
 [0.00000e+00 0.00000e+00 0.00000e+00 0.00000e+00 9.50625e+01 0.00000e+00
  0.00000e+00 0.00000e+00]
 [0.00000e+00 0.00000e+00 0.00000e+00 0.00000e+00 0.00000e+00 9.50625e+01
  0.00000e+00 0.00000e+00]
 [0.00000e+00 0.00000e+00 0.00000e+00 0.00000e+00 0.00000e+00 0.00000e+00
  1.00000e-10 0.00000e+00]
 [0.00000e+00 0.00000e+00 0.00000e+00 0.00000e+00 0.00000e+00 0.00000e+00
  0.00000e+00 9.50625e+01]]


In [1]:
import ipdb
import torch

In [3]:
x = torch.randn(4, 3, 128, 64)

ipdb.set_trace()  # Execution will pause here

y = x.mean(dim=1)
print(y.shape)

--Return--
None
> c:\users\tarek\appdata\local\temp\ipykernel_13616\2643665886.py(3)<module>()



ipdb>  p x.shape


torch.Size([4, 3, 128, 64])


ipdb>  whatis x


<class 'torch.Tensor'>


ipdb>  p y


*** NameError: name 'y' is not defined
--KeyboardInterrupt--

KeyboardInterrupt: Interrupted by user
torch.Size([4, 128, 64])


In [5]:
import torch
import torch.nn as nn
import ipdb

class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.conv1 = nn.Conv2d(3, 16, kernel_size=3, stride=1, padding=1)
        self.conv2 = nn.Conv2d(16, 32, kernel_size=3, stride=1, padding=1)

    def forward(self, x):
        x = self.conv1(x)
        ipdb.set_trace()  # Pause execution after first convolution
        x = self.conv2(x)
        return x

net = Net()
x = torch.randn(4, 3, 128, 64)
y = net(x)  # Execution will pause inside forward()


> c:\users\tarek\appdata\local\temp\ipykernel_13616\22276600.py(14)forward()



ipdb>  p x


tensor([[[[-4.8355e-01, -5.3310e-01, -1.0208e+00,  ..., -3.2801e-01,
            8.2928e-01,  1.0132e-01],
          [-2.6046e-01,  3.9874e-01,  7.1692e-01,  ..., -5.9388e-01,
           -1.7739e-01, -8.4276e-03],
          [-5.8490e-01, -1.5301e+00, -6.8830e-01,  ...,  1.0742e+00,
           -1.1980e-01, -6.2833e-01],
          ...,
          [ 7.5173e-02, -2.2512e-01, -3.2613e-01,  ...,  8.1433e-01,
            1.2678e+00, -3.8251e-01],
          [-7.1925e-01, -1.3520e+00, -3.6184e-01,  ..., -5.6472e-02,
           -1.6391e+00, -1.2781e-01],
          [ 3.8756e-01,  4.2653e-01, -5.6158e-01,  ..., -5.4772e-01,
            2.7698e-01,  1.0416e-01]],

         [[-6.1899e-01, -5.9339e-01, -8.4567e-01,  ...,  1.5528e-01,
            2.2720e-01,  6.4080e-03],
          [-1.8170e-01, -4.9712e-02,  6.0938e-01,  ..., -2.9470e-02,
            2.2378e-01, -7.3413e-02],
          [-6.3397e-01, -9.4494e-01, -1.1954e+00,  ...,  1.0526e+00,
           -2.5076e-01, -6.5697e-01],
          ...,
     

ipdb>  p x.shape


torch.Size([4, 16, 128, 64])
--KeyboardInterrupt--

KeyboardInterrupt: Interrupted by user
